import './globals.css'
import localFont from 'next/font/local'

const codec = localFont({
  src: [
    {
      path: '../../public/fonts/Codec-Pro-Extralight.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Codec-Pro-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Codec-Pro-Bold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Codec-Pro-Extrabold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-codec',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${codec.variable} font-sans`}>{children}</body>
    </html>
  )
}
